# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
  - trigger: ":red"
    replace: "'<font color=red>$|$</font>"
  - trigger: ":red"
    replace: "'<font color=red><strong>$|$</strong></font>"
  - trigger: ":red"
    replace: "'<font color=red><strong><em>$|$</em></strong></font>"
  
  - trigger: ":em"
    replace: "'*$|$*"
  - trigger: ":em"
    replace: "'<font color=red><em>$|$</em></font>"
  - trigger: ":em"
    replace: "'<font color=red><strong><em>$|$</em></strong></font>"
  
  - trigger: ":under"
    replace: "'<u>$|$</u>"

  - trigger: "del"
    replace: "'<del>$|$</del>"

  - trigger: ":bold"
    replace: "'<strong>$|$</strong>"
  - trigger: ":strong"
    replace: "'<strong>$|$</strong>"
  
  - trigger: ":log"
    replace: "'<span style=\"background:rgba(5, 117, 197, 0.2)\">$|$</span>"
  - trigger: ":log"
    replace: "'<span style=\"background:rgba(5, 117, 197, 0.2)\"><font color=red>$|$</font></span>"
  
  - trigger: ":async"
    replace: "'<font color=\"#00b050\">$|$</font>"

  - trigger: ":poly"
    replace: "'<span style=\"background:#fdbfff\">$|$</span>"
  - trigger: ":poly"
    replace: "'<span style=\"background:#fdbfff\"><font color=red>$|$</font></span>"
  
  - trigger: ":anchorb"
    replace: "'<font color=\"#2F6EBB\"><strong><em><u>"
  - trigger: ":anchore"
    replace: "</u></em></strong></font>"
  
  - trigger: ":memory"
    replace: "'<span style=\"background:rgba(240, 200, 0, 0.2)\">$|$</span>"
  
  - trigger: ":param"
    replace: "'<font color=\"#4FADEA\"><strong>$|$</strong></font>"
  
  - trigger: ":cvar"
    replace: "'<span style=\"background:#9254de\"><font color=white>$|$</font></span>"
  
  - trigger: ":resource"
    replace: "'<span style=\"background:#A3CBFA\">$|$</span>"

  - trigger: ":pass"
    replace: "'<span style=\"background:#F6C243\"><em>$|$</em></span>"
  
  - trigger: ":return"
    replace: "'<span style=\"background:#000000\"><font color=white>$|$</font></span>"
  
  - trigger: ":question"
    replace: "'<span style=\"background:red\"></span>"
  
  - trigger: ":proc1"
    replace: "'<span style=\"background:#B02418; padding:5px\"><font color=white>$|$</font></span>"
  - trigger: ":proc2"
    replace: "'<span style=\"background:#67349A; padding:5px\"><font color=white>$|$</font></span>"
  - trigger: ":proc3"
    replace: "'<span style=\"background:#306EBA; padding:5px\"><font color=white>$|$</font></span>"
  - trigger: ":proc4"
    replace: "'<span style=\"background:#7A611D; padding:5px\"><font color=white>$|$</font></span>"
  
  - trigger: ":thread"
    replace: "'<span style=\"background:#659D98\"><font color=white>$|$</font></span>"
  
  - trigger: ":rd"
    replace: "'<span style=\"background:#75FB4C\"><font color=black>$|$</font></span>"